/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package packageView;

/**
 *
 * @author Charley
 */
public class Destinataire extends javax.swing.JFrame {

    /**
     * Creates new form Destinataire
     */
    public Destinataire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rechDestLab = new javax.swing.JLabel();
        jSeparatorDest = new javax.swing.JSeparator();
        codePLab = new javax.swing.JLabel();
        codePostal = new javax.swing.JTextField();
        nomLab = new javax.swing.JLabel();
        prenLab = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        jButtonRechDest = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        insertion = new javax.swing.JMenu();
        modification = new javax.swing.JMenu();
        suppression = new javax.swing.JMenu();
        listing = new javax.swing.JMenu();
        recherche = new javax.swing.JMenu();
        destinataire = new javax.swing.JMenuItem();
        livraison = new javax.swing.JMenuItem();
        livraisondate = new javax.swing.JMenuItem();
        quitter = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 100, 0, 0));
        setResizable(false);

        rechDestLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rechDestLab.setText("Recherche par Destinataire");
        rechDestLab.setMaximumSize(new java.awt.Dimension(200, 50));
        rechDestLab.setMinimumSize(new java.awt.Dimension(200, 50));
        rechDestLab.setPreferredSize(new java.awt.Dimension(200, 50));

        codePLab.setText("Code Postal: ");

        nomLab.setText("Nom: ");

        prenLab.setText("Prénom: ");

        jButtonRechDest.setText("Lancer la recherche!");
        jButtonRechDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRechDestActionPerformed(evt);
            }
        });

        insertion.setText("Insertion");
        insertion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                insertionMousePressed(evt);
            }
        });
        jMenuBar1.add(insertion);

        modification.setText("Modification");
        modification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modificationMousePressed(evt);
            }
        });
        jMenuBar1.add(modification);

        suppression.setText("Suppression");
        suppression.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                suppressionMousePressed(evt);
            }
        });
        jMenuBar1.add(suppression);

        listing.setText("Listing");
        listing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listingMousePressed(evt);
            }
        });
        jMenuBar1.add(listing);

        recherche.setText("Recherche");

        destinataire.setText("Destinataire");
        destinataire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                destinataireMousePressed(evt);
            }
        });
        recherche.add(destinataire);

        livraison.setText("Livraison");
        livraison.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                livraisonMousePressed(evt);
            }
        });
        recherche.add(livraison);

        livraisondate.setText("Livraison par date");
        livraisondate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                livraisondateMousePressed(evt);
            }
        });
        recherche.add(livraisondate);

        jMenuBar1.add(recherche);

        quitter.setText("Quitter");
        quitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                quitterMousePressed(evt);
            }
        });
        jMenuBar1.add(quitter);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparatorDest)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rechDestLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRechDest, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomLab)
                            .addComponent(prenLab)
                            .addComponent(codePLab))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rechDestLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenLab)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomLab)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codePLab)
                    .addComponent(codePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonRechDest)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertionMousePressed
        new Insertion().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_insertionMousePressed

    private void modificationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificationMousePressed
        new Modification().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modificationMousePressed

    private void suppressionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppressionMousePressed
        new Suppression().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_suppressionMousePressed

    private void listingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listingMousePressed
        new Listing().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_listingMousePressed

    private void destinataireMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destinataireMousePressed
        new Destinataire().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_destinataireMousePressed

    private void livraisonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_livraisonMousePressed
        new Livraison().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_livraisonMousePressed

    private void livraisondateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_livraisondateMousePressed
        new LivraisonDate().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_livraisondateMousePressed

    private void quitterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitterMousePressed
        System.exit(0);
    }//GEN-LAST:event_quitterMousePressed

    private void jButtonRechDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRechDestActionPerformed
      String prnm,nm;
      int codePo;
      prnm=prenom.getText();
      nm=nom.getText();
      codePo=Integer.parseInt(codePostal.getText());
      
    }//GEN-LAST:event_jButtonRechDestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Destinataire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Destinataire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Destinataire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Destinataire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Destinataire().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codePLab;
    private javax.swing.JTextField codePostal;
    private javax.swing.JMenuItem destinataire;
    private javax.swing.JMenu insertion;
    private javax.swing.JButton jButtonRechDest;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparatorDest;
    private javax.swing.JMenu listing;
    private javax.swing.JMenuItem livraison;
    private javax.swing.JMenuItem livraisondate;
    private javax.swing.JMenu modification;
    private javax.swing.JTextField nom;
    private javax.swing.JLabel nomLab;
    private javax.swing.JLabel prenLab;
    private javax.swing.JTextField prenom;
    private javax.swing.JMenu quitter;
    private javax.swing.JLabel rechDestLab;
    private javax.swing.JMenu recherche;
    private javax.swing.JMenu suppression;
    // End of variables declaration//GEN-END:variables
}
