/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package packageView;

/**
 *
 * @author Charley
 */
public class Livraison extends javax.swing.JFrame {

    /**
     * Creates new form Livraison
     */
    public Livraison() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rechLivLab = new javax.swing.JLabel();
        jSeparatorLiv = new javax.swing.JSeparator();
        nomExpLab = new javax.swing.JLabel();
        nomDestLab = new javax.swing.JLabel();
        codePLab = new javax.swing.JLabel();
        nomExp = new javax.swing.JTextField();
        nomDest = new javax.swing.JTextField();
        codePostal = new javax.swing.JTextField();
        jButtonRechLiv = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        insertion = new javax.swing.JMenu();
        modification = new javax.swing.JMenu();
        suppression = new javax.swing.JMenu();
        listing = new javax.swing.JMenu();
        recherche = new javax.swing.JMenu();
        destinataire = new javax.swing.JMenuItem();
        livraison = new javax.swing.JMenuItem();
        livraisondate = new javax.swing.JMenuItem();
        quitter = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 100, 0, 0));
        setResizable(false);

        rechLivLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rechLivLab.setText("Recherche par Livraison");
        rechLivLab.setMaximumSize(new java.awt.Dimension(200, 50));
        rechLivLab.setMinimumSize(new java.awt.Dimension(200, 50));
        rechLivLab.setPreferredSize(new java.awt.Dimension(200, 50));

        nomExpLab.setText("Nom de l'expéditeur: ");

        nomDestLab.setText("Nom du destinataire: ");

        codePLab.setText("Code Postal: ");

        jButtonRechLiv.setText("Lancer la recherche!");

        insertion.setText("Insertion");
        insertion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                insertionMousePressed(evt);
            }
        });
        jMenuBar1.add(insertion);

        modification.setText("Modification");
        modification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modificationMousePressed(evt);
            }
        });
        jMenuBar1.add(modification);

        suppression.setText("Suppression");
        suppression.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                suppressionMousePressed(evt);
            }
        });
        jMenuBar1.add(suppression);

        listing.setText("Listing");
        listing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listingMousePressed(evt);
            }
        });
        jMenuBar1.add(listing);

        recherche.setText("Recherche");

        destinataire.setText("Destinataire");
        destinataire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                destinataireMousePressed(evt);
            }
        });
        recherche.add(destinataire);

        livraison.setText("Livraison");
        livraison.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                livraisonMousePressed(evt);
            }
        });
        recherche.add(livraison);

        livraisondate.setText("Livraison par date");
        livraisondate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                livraisondateMousePressed(evt);
            }
        });
        recherche.add(livraisondate);

        jMenuBar1.add(recherche);

        quitter.setText("Quitter");
        quitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                quitterMousePressed(evt);
            }
        });
        jMenuBar1.add(quitter);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparatorLiv, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 250, Short.MAX_VALUE)
                .addComponent(rechLivLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRechLiv, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomDestLab)
                            .addComponent(codePLab)
                            .addComponent(nomExpLab))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomExp, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(nomDest)
                            .addComponent(codePostal))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rechLivLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorLiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomExpLab)
                    .addComponent(nomExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomDestLab)
                    .addComponent(nomDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codePLab)
                    .addComponent(codePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonRechLiv)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertionMousePressed
        new Insertion().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_insertionMousePressed

    private void modificationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificationMousePressed
        new Modification().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modificationMousePressed

    private void suppressionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppressionMousePressed
        new Suppression().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_suppressionMousePressed

    private void listingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listingMousePressed
        new Listing().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_listingMousePressed

    private void destinataireMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destinataireMousePressed
        new Destinataire().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_destinataireMousePressed

    private void livraisonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_livraisonMousePressed
        new Livraison().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_livraisonMousePressed

    private void livraisondateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_livraisondateMousePressed
        new LivraisonDate().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_livraisondateMousePressed

    private void quitterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitterMousePressed
        System.exit(0);
    }//GEN-LAST:event_quitterMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Livraison().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codePLab;
    private javax.swing.JTextField codePostal;
    private javax.swing.JMenuItem destinataire;
    private javax.swing.JMenu insertion;
    private javax.swing.JButton jButtonRechLiv;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparatorLiv;
    private javax.swing.JMenu listing;
    private javax.swing.JMenuItem livraison;
    private javax.swing.JMenuItem livraisondate;
    private javax.swing.JMenu modification;
    private javax.swing.JTextField nomDest;
    private javax.swing.JLabel nomDestLab;
    private javax.swing.JTextField nomExp;
    private javax.swing.JLabel nomExpLab;
    private javax.swing.JMenu quitter;
    private javax.swing.JLabel rechLivLab;
    private javax.swing.JMenu recherche;
    private javax.swing.JMenu suppression;
    // End of variables declaration//GEN-END:variables
}
