/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package packageView;

import javax.swing.JOptionPane;

/**
 *
 * @author Charley
 */
public class Suppression extends javax.swing.JFrame {

    /**
     * Creates new form Suppression
     */
    public Suppression() {
        this.addWindowListener(new WindowListenerClose());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        suppressionLab = new javax.swing.JLabel();
        jSeparatorSupp = new javax.swing.JSeparator();
        numLivLab = new javax.swing.JLabel();
        numLiv = new javax.swing.JTextField();
        jButtonRechSup = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        insertion = new javax.swing.JMenu();
        modification = new javax.swing.JMenu();
        suppression = new javax.swing.JMenu();
        listing = new javax.swing.JMenu();
        recherche = new javax.swing.JMenu();
        destinataire = new javax.swing.JMenuItem();
        livraison = new javax.swing.JMenuItem();
        livraisondate = new javax.swing.JMenuItem();
        quitter = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 100, 0, 0));
        setResizable(false);

        suppressionLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        suppressionLab.setText("Suppression");
        suppressionLab.setMaximumSize(new java.awt.Dimension(200, 50));
        suppressionLab.setMinimumSize(new java.awt.Dimension(200, 50));
        suppressionLab.setPreferredSize(new java.awt.Dimension(200, 50));

        numLivLab.setText("Numéro de livraison: ");

        jButtonRechSup.setText("Supprimer !");
        jButtonRechSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRechSupActionPerformed(evt);
            }
        });

        insertion.setText("Insertion");
        insertion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                insertionMousePressed(evt);
            }
        });
        jMenuBar1.add(insertion);

        modification.setText("Modification");
        modification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modificationMousePressed(evt);
            }
        });
        jMenuBar1.add(modification);

        suppression.setText("Suppression");
        suppression.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                suppressionMousePressed(evt);
            }
        });
        jMenuBar1.add(suppression);

        listing.setText("Listing");
        listing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listingMousePressed(evt);
            }
        });
        jMenuBar1.add(listing);

        recherche.setText("Recherche");

        destinataire.setText("Destinataire");
        destinataire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                destinataireMousePressed(evt);
            }
        });
        recherche.add(destinataire);

        livraison.setText("Livraison");
        livraison.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                livraisonMousePressed(evt);
            }
        });
        recherche.add(livraison);

        livraisondate.setText("Livraison par date");
        livraisondate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                livraisondateMousePressed(evt);
            }
        });
        recherche.add(livraisondate);

        jMenuBar1.add(recherche);

        quitter.setText("Quitter");
        quitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                quitterMousePressed(evt);
            }
        });
        jMenuBar1.add(quitter);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(suppressionLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
            .addComponent(jSeparatorSupp)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRechSup, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numLivLab)
                        .addGap(18, 18, 18)
                        .addComponent(numLiv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(suppressionLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorSupp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numLivLab)
                    .addComponent(numLiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonRechSup)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertionMousePressed
        new Insertion().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_insertionMousePressed

    private void modificationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificationMousePressed
        new Modification().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modificationMousePressed

    private void suppressionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppressionMousePressed
        new Suppression().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_suppressionMousePressed

    private void listingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listingMousePressed
        new Listing().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_listingMousePressed

    private void destinataireMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destinataireMousePressed
        new Destinataire().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_destinataireMousePressed

    private void livraisonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_livraisonMousePressed
        new Livraison().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_livraisonMousePressed

    private void livraisondateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_livraisondateMousePressed
        new LivraisonDate().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_livraisondateMousePressed

    private void quitterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitterMousePressed
        System.exit(0);
    }//GEN-LAST:event_quitterMousePressed

    private void jButtonRechSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRechSupActionPerformed
        String numeroLiv;
        numeroLiv= numLiv.getText();
        int n = JOptionPane.showConfirmDialog(null, "Etes-vous sur de vouloir supprimer la livraison "+numeroLiv+"?", "Etes-vous sur de vouloir supprimer cette livraison?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (n == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(null,"La livraison "+numeroLiv+" a été supprimée!","Livraison supprimée!",JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        new Main().setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_jButtonRechSupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Suppression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Suppression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Suppression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Suppression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Suppression().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem destinataire;
    private javax.swing.JMenu insertion;
    private javax.swing.JButton jButtonRechSup;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparatorSupp;
    private javax.swing.JMenu listing;
    private javax.swing.JMenuItem livraison;
    private javax.swing.JMenuItem livraisondate;
    private javax.swing.JMenu modification;
    private javax.swing.JTextField numLiv;
    private javax.swing.JLabel numLivLab;
    private javax.swing.JMenu quitter;
    private javax.swing.JMenu recherche;
    private javax.swing.JMenu suppression;
    private javax.swing.JLabel suppressionLab;
    // End of variables declaration//GEN-END:variables
}
